### ISSUE TITLE
Third part of the series?

### ISSUE THREAD

**Issue by ChristianHuff-DEV** [jerriepelser-blog/auth0-vue-oidc-client#1]
Hello @jerriep,

I am currently trying to wrap my head around OAuth and how to implement it in a Vue.js application.
I stumbled across your excellent blog posts and was excited to read that in the third part you'll show how to implement the renewal of the access token.

Is there any chance you'll write that third part? Or that you publish the code for it? (Or maybe you did and I just didn't find the correct part where you do the renewal.)

Kind regards
Christian

**Comment by jerriep** [comment]
No sorry, I never got around to that.
